# Generated by Django 5.1.3 on 2024-11-19 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buzz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buzz",
            old_name="photos",
            new_name="photo",
        ),
    ]
